# **Political Counseling:** Where "Civil" Discourse Begins {#civil-discourse}

#### Keywords {-}

politics, democracy, vote, elections, cognitive bias, tribalism

## Tribalism in American Politics

In the last couple of decades, there has been a growing sense of a widening chasm in American politics where the divide is defined more by regional demographics and cultural identity than simply a difference of opinion regarding public policy. This dysfunctional political landscape is now so widely acknowledged that Geoff Nunberg of NPR’s “Fresh Air” radio program declared “tribalism” the word of 2017 [@NunbergFissuresPoliticalCamps].

Because there is an explicit “winner” and “loser” in each election, there is a natural propensity for voters to adopt an “us” versus “them” mentality. Further, an individual is much more likely to be influenced by their geography, class, friends, and family when supporting a candidate as opposed to their own political ideals. Upon identifying with a particular party, the political divide is further entrenched by social media and preferred news outlets that validate and reinforce their party’s rhetoric. As a consequence, Andrew Sullivan of the Washington Post describes the two tribes in American politics as “fighting not just to advance their own side but to provoke, condemn, and defeat the other” [@SullivanCanOurDemocracy2017].  Robert Reich, the Chancellor’s Professor of Public Policy at University of California at Berkeley, more strongly asserts that both the Republican and Democratic parties “are pulling America apart, often putting tribal goals over the national interest” [@ReichNewTribalismDecline].

Most tools that aim to empower the American voter focus on boosting voter turnout or rallying support for a particular party, concern, or politician. However, the United States will likely continue this trend of “mutual incomprehension” and acrimony without an effort to improve the way we communicate with each other regarding important issues impacting the nation. The Civil Discourse web app aspires to be an interactive tool that reintroduces human complexity into our political system [@GersonOpinionTribalismtriumphs2017] and allow the user to view members of an opposing political group as unique individuals as opposed to hostile outsiders. By focusing on commonalities and obfuscating party lines, Civil Discourse intends to introduce nuance and respect to our nation's dialogue.

## Prioritizing Political Ideals
Just as the "Big Five" personality model [@costa_revised_1992] & [@norman_toward_1963] aims to represent how a person engages with the world based on five generalized personality traits, the Civil Discourse web app will create a *political* profile of current American congressmen and senators based on their position on previous legislation.

First, a core set of political ideals will be identified and defined, such as limited government, equality, social insurance, individual rights & freedoms, the environment, and foreign policy. Since ideals are a social construct, an initial dataset will consist of a random sampling of past bills that are manually rated and classified according to their relevance to the previously defined ideals based on the human interpretation of several individuals. A natural language processing model will then be designed using the initial, manually classified training set to assign weights for each defined political ideal to a larger, more comprehensive set of legislation as well as any new bills that are voted upon. By aggregating the model weights of each bill that a politician supports or opposes as evident by his voting record, a profile can be produced to score a politician’s position on each stance.

In a similar manner, an American voter visiting the Civil Discourse web app can create his or her own political profile by completing a questionnaire analogous to how someone may take an online personality test. In addition, the user will specify his or her political party as an input. This may seem counter-productive to the tool’s goal of overcoming division. However, the intent is to highlight compatible viewpoints from politicians of a political group that is different from the user’s own party.
Often, a tool of this type will narrow the focus of the user to match him or her with the political candidate that is the best *overall* match to their political disposition. In contrast, the Civil Discourse app will broaden the perspective of the user to consider politicians that may not have the political profile *most* congruent with the user but may strongly support or oppose a common stance that is weighted highly on the user’s results. The goal is to regard politicians on a political spectrum as opposed to a binary categorization.
The end product will be a political profile of the user, similar to a personality profile, along with a list of three politicians from an opposing party that share a strong conviction on a matching ideal. The user can then interact with the results to explore which policies the listed politicians supported or opposed that weighted them similarly to the user on that stance. In addition, the user will be encouraged to share their results on social media, such as Facebook or Twitter, so that their friends and family can use the tool for their own introspection.

## Leveraging the Affect Heuristic

There are two desired outcomes from using the Civil Discourse web app. The user will 1) focus on commonalities between parties to speak more respectfully regarding differences & 2) vote for a politician based on voting record as opposed to rhetoric. For example, a politician may claim to support the military but then fail to support a measure that would continue paying military personnel during a government shutdown. Though transparency is important, the second outcome is not a primary or likely goal.

In many ways, the dynamic between America’s two major political parties is similar to that of a broken marriage. The focus has shifted from wanting to solve the nation’s problems to winning at all costs. There are a number of cognitive biases that contribute to this problem, and it is likely that those that are already open-minded to differing viewpoints will be attracted to this tool. One such cognitive bias, the affect heuristic, encourages the political divide by simplifying our lives into an overly tidy framework. However, the Civil Discourse web app will leverage that same cognitive bias in a positive way by presenting compatible viewpoints from politicians of a different party in hopes of changing the "emotional appeal" of that group to the user [@kahneman_thinking_2011].
