# **Quantitative Therapy:** Monitoring the Inner Self {#quantitative-therapy}

#### Keywords {-}

mental health, cognitive behavioral therapy, medication management, psychiatry, sentiment analysis, emotion, metrics, nlp, natural language processing

## Unreliable Narrators and Sparse Sampling

In general, mental health practitioners must rely heavily on the self-reporting of patients to gauge the efficacy of therapy or prescribed medication. However, a patient's assessment of their own progress can be influenced by their immediate state at the time of their appointment, and the nature of their condition may further alter their self-perception. In addition, doctors and therapists usually only see their patients once a week or even more infrequently. This may cause aliasing when trying to determine trends or patterns in patient behaviour or symptoms. Journaling is a common recommendation in cognitive behavioural therapy for patients to process their thoughts and emotions. In a study investigating the effectiveness of expressive writing in outpatient psychotherapy, the individuals in the written emotional disclosure group demonstrated significant improvement in their anxiety and depression compared to the control group [@graf_written_2008]. Often, the action of journaling itself is emphasized as therapeutic for the patient, but the qualitative data from the resulting journal entries can potentially provide further insight into the patient’s emotional state at a much finer frequency than appointments alone. By using a natural processing model combined with a therapist or doctor’s expert observations to obtain emotional metrics from daily journal entries, a mental health professional can monitor the progress of their patient more reliably.

## Metrics and Trends from Journaling

For this project to be successful, we must understand how changes in mental and emotional health are reflected in an individual’s writing. To investigate this question, we must acquire a dataset that includes a collection of writing from individuals based on a standard set of prompts that are qualitatively classified by experts according to a model of emotions, such as Plutchik’s wheel of emotions. Dr. Robert Plutchik defined four sets of opposing emotions: joy and sadness, trust and disgust, fear and anger, as well as surprise and anticipation. The combinations of the primary emotions as well as the change in intensity result in new emotional categories. For example, the combination of joy and anticipation yields optimism, and an increase in intensity transforms sadness to grief [@plutchik_emotions_1991].

This initial classified dataset can then be used to train a natural language processing model that will be the foundation for the proposed product, which will accept daily electronic journal entries of patients. The outputs of the model will include weights for general positive and negative sentiments as well as for categories of emotions identified in the writing.
The deployment of the model will involve building a secure web app with two main components: a patient facing interface for writing journal entries that will become the model inputs and a dashboard for mental health professionals that will display metrics and trends derived from the model outputs. Absolute metrics on individual journal entries, such as emotion weights, may be of limited value. However, relative trends or the change over time in each metric for an individual patient may be more insightful. For example, the model outputs for a particular journal entry may specify 80% apprehension and 20% interest. The heavy proportion of apprehension expressed in the writing may be alarming out of context. However, this may be close to the baseline for the patient. A more significant finding would be if the proportion of apprehension was a result of an increasing trend that was not deterred by treatment. During patient appointments, doctors will have the opportunity to compare model outputs with their own expert judgement. If there is a significant difference, they can correct the results which will then be used to calibrate the model for future runs. Expert diagnoses and patient data are anonymized and used to augment the main model to increase robustness with use.


## Empower Doctors and Therapists

Instead of relying on brief windows of observation during a patient's appointment with their mental health professional, doctors and therapists can use the quantitative metrics and trends from the sentiment analysis of daily journal entries to augment their expertise and make more informed decisions regarding changes in medication or therapy strategies. In addition, access to data on a daily scale prevents the possibility of being overly influenced by anomalously low or high symptoms at the time of a patient’s appointment.

The content of the journal entries would only be accessible to the patient as well as his or her mental health professional and would be respected by the same confidentiality between patient and doctor as the content of in-person appointments. Since the journal is shared with the doctor or therapist, the patient may censor their writing just as he or she may not be completely forthright while answering questions during an appointment. However, the natural language processing model may identify subtle patterns in word choice or structure that are clues to the inner state of the patient which may not be otherwise apparent to the doctor.

In the future, additional types of monitoring data, such as heart rate, may be integrated to provide mental health professionals with a more holistic view of their patients. Alternative forms of monitoring data may be essential in circumstances where journaling may be harmful to the patient or where there are problems with patient adherence to medical advice.

The end goal is to provide tools and guidance that allow for more consistent diagnosis and monitoring of mental illness, regardless of the variance in intuition amongst mental health professionals or the ability of the patient to accurately report their condition.
